### ISSUE TITLE
AddressBadge component

### ISSUE THREAD

**Issue by jounih** [aragon/design#3]
<img width="838" alt="screen shot 2018-10-18 at 12 28 45" src="https://user-images.githubusercontent.com/10109867/47151354-663be800-d2d1-11e8-99bb-7dfaca18e3b2.png">

A new proposed design for an address badge component, to be used whenever an entity name/ethereum address is need to display on the Aragon UI.

The design follows the initial proposal by @bpierre - [https://github.com/aragon/aragon-ui/issues/156#issuecomment-385998267](https://github.com/aragon/aragon-ui/issues/156#issuecomment-385998267)

The rationale is that it should be very easy for users to visually distinguish in the UI when an entity is being referred to, and effortless to find out more information about that entity.

We allow shortening of long entity names/addresses where space doesn't allow for the full address, and by making the badge clickable we display the complete Ethereum address, make it very easy to copy the address, and make it easy to open the Etherscan url in another tab for more information.

**Comment by luisivan** [comment]
Something I was thinking: maybe emoji combinations, like the one Telegram uses (https://telegram.org/blog/calls) would be more user friendly than identicons. Thoughts?

**Comment by stellarmagnet** [comment]
Looking forward to this component!

1) Some thoughts to help with "DAO founder doppelgängers" is to also have some kind of special "verified" (Twitter-like) badge, so then for example, let's say I am an ANT holder, we end up knowing who the real "Luis Iván Cuende" really is, and someone else can't assume his entity when creating votes and tricking people into thinking it was Luis who created the vote. 

Relating to this, we may want to also set a specific permission for who in the DAO can grant this "verified" badge to other people too?

Perhaps the DAO founders can be the initial set of "identity validators" / people who vouch for other identities within the DAO (I know this adds some element of centralization, but we all know very well how much of a problem identity is on Twitter).

- Can also use Keybase as a form of validator as well - the DAO founders use Keybase/social proofs as an "oracle" to validate people's identities (for people they don't personally know). 
- Or maybe instead of using Keybase, there is a Twitter/Github integration to post your DAO address as an issue in an "Aragon Identity Validator" repo or as a Tweet, to map your identity as a social proof independent of Keybase.
- But the DAO founder way may be a good enough near-term solution, perhaps with a Veto option for members of the DAO to contest a verified badge, if members of the DAO have some proof of manipulation.
- There can also be a vote for other members of the DAO who want to help with this identity validation / Sybil Detection for doppelgängers.The term for these people may be "Sybil Detection Good Samaritans aka Sybil Detectives", and the founders begin with this role, then later transfer it over to the Sybil Detectives.

2) Can you explain the design reasoning for why the address in the popup has a blue background color? Is it only blue once the copy to clipboard icon is clicked, or is it always meant to be blue like this?
![image](https://user-images.githubusercontent.com/2584493/43363105-54ab4552-9359-11e8-9c7e-adf95e502c5b.png)

**Comment by luisivan** [comment]
I'm 99% sure that the background is only blue when selected to copy @stellarmagnet

**Comment by stellarmagnet** [comment]
Does the current architecture support autocomplete throughout all Aragon Apps for the "Recipient" address fields, tying it to the Identity app, or do enhancements need to be made to support this paradigm?

**Comment by luisivan** [comment]
Aragon UI will provide this component which will take care of everything for developers :+1:

**Comment by stellarmagnet** [comment]
I'm trying to find out more details because i'm wondering the complexity of integrating another app to read data from, to populate the autocomplete (e.g. one of the apps part of our planning suite - Address Book, which is useful for managing frequently used addresses of non-DAO members - which can be individuals, projects, multisigs, etc)

**Comment by luisivan** [comment]
I think that would be totally doable. In your local DAO settings, you could select identity registries that you wanna be able to autoselect from

**Comment by tayvano** [comment]
Truncation should be 0x + first four characters + ... + last four characters.

**Comment by luisivan** [comment]
Totally agree @tayvano! That's what we are using now for the product, but seems like the mockups weren't updated. Thanks for chiming in!

**Comment by jounih** [comment]
Ah yes this has already been updated in sketch file but had the old jpg here - updated :) Thanks for noticing!
